use ami;
drop table if exists misspellings;
create table misspellings (
	incorrect varchar(32) not null primary key,
	correct varchar(32) not null
);
insert into misspellings (correct, incorrect) values ('accommodate', 'accomodate');
insert into misspellings (correct, incorrect) values ('accommodation', 'accomodation');
insert into misspellings (correct, incorrect) values ('achieve', 'acheive');
insert into misspellings (correct, incorrect) values ('across', 'accross');
insert into misspellings (correct, incorrect) values ('aggressive', 'agressive');
insert into misspellings (correct, incorrect) values ('aggression', 'agression');
insert into misspellings (correct, incorrect) values ('apparently', 'apparantly');
insert into misspellings (correct, incorrect) values ('appearance', 'appearence');
insert into misspellings (correct, incorrect) values ('argument', 'arguement');
insert into misspellings (correct, incorrect) values ('assassination', 'assasination');
insert into misspellings (correct, incorrect) values ('basically', 'basicly');
insert into misspellings (correct, incorrect) values ('beginning', 'begining');
insert into misspellings (correct, incorrect) values ('believe', 'beleive, belive');
insert into misspellings (correct, incorrect) values ('bizarre', 'bizzare');
insert into misspellings (correct, incorrect) values ('business', 'buisness');
insert into misspellings (correct, incorrect) values ('calendar', 'calender');
insert into misspellings (correct, incorrect) values ('Caribbean', 'Carribean');
insert into misspellings (correct, incorrect) values ('cemetery', 'cemetary');
insert into misspellings (correct, incorrect) values ('chauffeur', 'chauffer');
insert into misspellings (correct, incorrect) values ('colleague', 'collegue');
insert into misspellings (correct, incorrect) values ('coming', 'comming');
insert into misspellings (correct, incorrect) values ('committee', 'commitee');
insert into misspellings (correct, incorrect) values ('completely', 'completly');
insert into misspellings (correct, incorrect) values ('conscious', 'concious');
insert into misspellings (correct, incorrect) values ('curiosity', 'curiousity');
insert into misspellings (correct, incorrect) values ('definitely', 'definately');
insert into misspellings (correct, incorrect) values ('dilemma', 'dilemna');
insert into misspellings (correct, incorrect) values ('disappear', 'dissapear');
insert into misspellings (correct, incorrect) values ('disappoint', 'dissapoint');
insert into misspellings (correct, incorrect) values ('ecstasy', 'ecstacy');
insert into misspellings (correct, incorrect) values ('embarrass', 'embarass');
insert into misspellings (correct, incorrect) values ('environment', 'enviroment');
insert into misspellings (correct, incorrect) values ('existence', 'existance');
insert into misspellings (correct, incorrect) values ('Fahrenheit', 'Farenheit');
insert into misspellings (correct, incorrect) values ('familiar', 'familar');
insert into misspellings (correct, incorrect) values ('finally', 'finaly');
insert into misspellings (correct, incorrect) values ('fluorescent', 'florescent');
insert into misspellings (correct, incorrect) values ('foreign', 'foriegn');
insert into misspellings (correct, incorrect) values ('foreseeable', 'forseeable');
insert into misspellings (correct, incorrect) values ('forty', 'fourty');
insert into misspellings (correct, incorrect) values ('forward', 'foward');
insert into misspellings (correct, incorrect) values ('friend', 'freind');
insert into misspellings (correct, incorrect) values ('further', 'futher');
insert into misspellings (correct, incorrect) values ('gist', 'jist');
insert into misspellings (correct, incorrect) values ('glamorous', 'glamourous');
insert into misspellings (correct, incorrect) values ('government', 'goverment');
insert into misspellings (correct, incorrect) values ('guard', 'gaurd');
insert into misspellings (correct, incorrect) values ('happened', 'happend');
insert into misspellings (correct, incorrect) values ('harass', 'harrass');
insert into misspellings (correct, incorrect) values ('harassment', 'harrassment');
insert into misspellings (correct, incorrect) values ('honorary', 'honourary');
insert into misspellings (correct, incorrect) values ('humorous', 'humourous');
insert into misspellings (correct, incorrect) values ('idiosyncrasy', 'idiosyncracy');
insert into misspellings (correct, incorrect) values ('immediately', 'immediatly');
insert into misspellings (correct, incorrect) values ('incidentally', 'incidently');
insert into misspellings (correct, incorrect) values ('independent', 'independant');
insert into misspellings (correct, incorrect) values ('interrupt', 'interupt');
insert into misspellings (correct, incorrect) values ('irresistible', 'irresistable');
insert into misspellings (correct, incorrect) values ('knowledge', 'knowlege');
insert into misspellings (correct, incorrect) values ('liaise', 'liase');
insert into misspellings (correct, incorrect) values ('liaison', 'liason');
insert into misspellings (correct, incorrect) values ('lollipop', 'lollypop');
insert into misspellings (correct, incorrect) values ('millennium', 'millenium');
insert into misspellings (correct, incorrect) values ('millennia', 'millenia');
insert into misspellings (correct, incorrect) values ('Neanderthal', 'Neandertal');
insert into misspellings (correct, incorrect) values ('necessary', 'neccessary');
insert into misspellings (correct, incorrect) values ('noticeable', 'noticable');
insert into misspellings (correct, incorrect) values ('occasion', 'ocassion, occassion');
insert into misspellings (correct, incorrect) values ('occurred', 'occured');
insert into misspellings (correct, incorrect) values ('occurring', 'occuring');
insert into misspellings (correct, incorrect) values ('occurrence', 'occurance, occurence');
insert into misspellings (correct, incorrect) values ('pavilion', 'pavillion');
insert into misspellings (correct, incorrect) values ('persistent', 'persistant');
insert into misspellings (correct, incorrect) values ('pharaoh', 'pharoah');
insert into misspellings (correct, incorrect) values ('piece', 'peice');
insert into misspellings (correct, incorrect) values ('politician', 'politican');
insert into misspellings (correct, incorrect) values ('Portuguese', 'Portugese');
insert into misspellings (correct, incorrect) values ('possession', 'posession');
insert into misspellings (correct, incorrect) values ('preferred', 'prefered');
insert into misspellings (correct, incorrect) values ('preferring', 'prefering');
insert into misspellings (correct, incorrect) values ('propaganda', 'propoganda');
insert into misspellings (correct, incorrect) values ('publicly', 'publically');
insert into misspellings (correct, incorrect) values ('really', 'realy');
insert into misspellings (correct, incorrect) values ('receive', 'recieve');
insert into misspellings (correct, incorrect) values ('referred', 'refered');
insert into misspellings (correct, incorrect) values ('referring', 'refering');
insert into misspellings (correct, incorrect) values ('religious', 'religous');
insert into misspellings (correct, incorrect) values ('remember', 'rember, remeber');
insert into misspellings (correct, incorrect) values ('resistance', 'resistence');
insert into misspellings (correct, incorrect) values ('sense', 'sence');
insert into misspellings (correct, incorrect) values ('separate', 'seperate');
insert into misspellings (correct, incorrect) values ('siege', 'seige');
insert into misspellings (correct, incorrect) values ('successful', 'succesful');
insert into misspellings (correct, incorrect) values ('supersede', 'supercede');
insert into misspellings (correct, incorrect) values ('surprise', 'suprise');
insert into misspellings (correct, incorrect) values ('tattoo', 'tatoo');
insert into misspellings (correct, incorrect) values ('tendency', 'tendancy');
insert into misspellings (correct, incorrect) values ('therefore', 'therefor');
insert into misspellings (correct, incorrect) values ('threshold', 'threshhold');
insert into misspellings (correct, incorrect) values ('tomorrow', 'tommorow, tommorrow');
insert into misspellings (correct, incorrect) values ('tongue', 'tounge');
insert into misspellings (correct, incorrect) values ('truly', 'truely');
insert into misspellings (correct, incorrect) values ('unforeseen', 'unforseen');
insert into misspellings (correct, incorrect) values ('unfortunately', 'unfortunatly');
insert into misspellings (correct, incorrect) values ('until', 'untill');
insert into misspellings (correct, incorrect) values ('weird', 'wierd');
insert into misspellings (correct, incorrect) values ('wherever', 'whereever');
insert into misspellings (correct, incorrect) values ('which', 'wich');

 


