#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
whoami
pwd
ROOT=$(pwd)
./stop
mkdir -p logs
rm -f $ROOT/logs/run-*.log
SUSPEND="n"
ARGS=""
while (( "$#" )); do
	case $1 in
		suspend)
			SUSPEND="y"
			;;
		init)
			ARGS="init"
			;;
		*)
			echo "Unrecognized argument"
			exit 1
			;;
	esac
	shift
done
JVM_ARGS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=$SUSPEND,address=8000"
# JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
JAVA_HOME="/usr/lib/jvm/java-1.8.0"
$JAVA_HOME/bin/java -version
$JAVA_HOME/bin/java $JVM_ARGS -jar $(find target -name "*.jar") $ARGS\
  > $ROOT/logs/run-ami.log 2> $ROOT/logs/run-ami.err.log &
echo "$!" > $ROOT/logs/run-ami.pid
echo "running"